= Phase 1, Chapter 1

_Townfolks always like the Sheriff, but precious few a’ them take much of a
shine to being one. It takes a whole lot of gumption to get up in the morning,
knowing that all manner of trouble could be brewing. Trouble that you have to
look square in the eye and ask it to hustle itself out of town. Knowing that
any day some gunslinging hothead could blow into town with a six-shooter
carrying that fateful bullet with your name on it. Heck maybe all six have
your name on them, that’s the breaks._

_On a good day, you go home in one piece. On a better day, so do the rest of
the townfolks. You do your job, knowing that the better you do it, the more
attention you’ll attract from better gunslingers, eager to make themselves a
name by carving yours on a tombstone. Now you got to baby-sit some Mesarite,
who couldn’t find his arse with both hands. Luckily, he’s got you to lead him
by the nose, into some of the most dangerous country this side of The Forge.
They say the Marshalls always get their man, but sometimes getting yur man
just gets yah a whole lot a trouble._

The story begins in the wild frontiers “southwest” of The Forge in Danjukk
where a dangerous criminal has successfully robbed a train. The criminal,
‘Smiling’ Phil Paxton, is the leader of a vicious gang of outlaws and rebels,
who are fleeing the justice of The Mesas. The “government” of the Mesas
dispatched a single constable to capture the outlaw and return him to stand
trial. Unfortunately, “Smiling” Phil Paxton and his gang have fled into the
wastes, where Mesarite justice bears little weight.

This would be the end of the story, were it not for the fact that Paxton’s
gang has been implicated in the rebellion around Gateway in Darkpine Forest,
and has strong ties with the cannibal tribes of the wastes. Furthermore, the
train the gang robbed carried a shipment of military supplies destined for
Fort Krieger. Pretty much all the authorities fear that Paxton may be
intending to arm the tribes and spark an all-out war. Twelve cases of rifles,
a small-bore cannon and enough ammunition to make the army worried, have been
taken around The Forge and are believed to be making their way into the hands
of the some of the most violent tribes in the entire Dustbowl.

