= Phase 1, Chapter 1, Session 1

[quote, Posted on the Mesa Job boards]
_______________________________________________________________________________
As a duly commissioned officer in the Mesarite Marshalls, I am hereby
authorised to offer a bounty for the return of one Phillip Louis Paxton. The
Government of the Mesas will pay a bounty of $500 for the capture of said
criminal dead or alive, and a further $25 for each of his gang. To respond to
this posting, be at the Yvoras Train station no later than 6:00am sharp with
your equipment ready to be loaded.
_______________________________________________________________________________

A job called, so Mason Dixon and Te Schwarm Chuuk answered. They took the
posting and arrived at the train station as instructed. There they met both
the Constable, and one Professor Archivist Tel Set. Tel Set was there to take
contribute to and take advantage of the protection hired by the Constable, so
that a trip down to Edge's Spirit-rock mines would be uneventful.

After a brief introduction the group boarded the train to Edge. They spent the
four day trip both cleaning and preparing their gear, and getting to know one
another better. Te Schwarm Chuuk made some offhand comments about his
cannibalism that did not endear him to the Marshal, and from then on, Jeffery
took many walks from the cabin to "get some fresh air".

[quote, Constable Weatherington]
_______________________________________________________________________________
From what information I've been able to glean from our informants, I believe
that Paxton’s gang is headed to a small town south of The Forge called Edge.
The town used to be called Hopeful but since a great quake pitched a good part
of the town into a great hole in the earth and left the remainder sitting on
the lip of a and huge precipice, the town has simply been called Edge. While
dropping half the town into the earth could never be considered a good thing,
the veins of spirit-rock the cataclysm exposed did serve to revitalize the
economy, though they somehow kept the discovery secret for a couple of years.
Edge has been given a new lease on life. Prospectors, hustlers and drifters
are attracted to the town seeking their fortune.

Paxton’s sister Lara McFadden works in a saloon in Edge and I believe that
Paxton and his gang are traveling to meet up with his sister for some reason.
I know his gang is in the possession of five cases of military rifles and a
small-bore cannon, which he stole from a military shipment destined for Fort
Krieger. “Smiling” Phil Paxton is probably about to sell the rifles to the
Cannibals in the area. We need some hard proof to stop Paxton and prevent a
possible Cannibal war.
_______________________________________________________________________________

Upon arrival, the group retrieved their horses and headed into town. The
Marshall went to the local Constabulary to gain information from them and pay
proper courtesy, and the less conspicuous members of the party went to "The
Last Gulp" saloon to find and enquire upon Bill Paxton's sister, Lara
McFaddon.

[quote, Constable Weatherington]
_______________________________________________________________________________
Lara McFadden, Phil’s sister, works at the Last Gulp. At one time, she and her
husband Jack, owned a successful mining operation on the outskirts of town,
employing 25 miners, including Lara’s brother Phil. Apparently Phil loved his
brother-in-law as is he were his own flesh and blood; and from what I can
gather, many believed this was the only period of his life that Phil would
have described as happy. When the great quake decimated the town, Lara’s
husband and 12 other miners were trapped in the mine. Lara & Phil rushed into
town to get help, but the remaining half of the town was in flames and its
people had their own problems.

After the accident, Lara tried to make the mine work, but the damage and the
memories were too great. After a few months, she was forced to close it down
permanently and take a job in the local saloon. She has been here ever since.
_______________________________________________________________________________

After confronting Lara...

[quote, Lara McFaddon]
_______________________________________________________________________________
Phillip and I begged the townsfolk for help, but they ignored him, focusing
on their own problems. The miners died and Phil rode out of town, swearing
that he'd "return to wreak a terrible vengeance". I heard he eventually
drifted northwest into Darkpine and became known as “Smiling” Phil Paxton, for
the grim smile that is perpetually etched on his face. So it's been five
years, and now he's back; a bitter, violent man, with the will and power to
get his revenge.

I accepted my loss and put the past behind me, where it belongs – until two
days ago when what passes for my younger brother drifted back into her life.

Phil has brought with him all the rage and pain he has been carrying with him
all these years. He told me he was going to make them all pay; that he’d found
a way to get his revenge on the townsfolk and a few days from now they'd all
be dead. I tried to reason with him, but he was crazed with hatred. We argued,
but Phil forced me to take $200 and left. The last thing he said to me was:

“If you ain’t out o’ town in two, three days max, I ain’t goin’ to be
responsible for what happens!
_______________________________________________________________________________

