= Phase 1, Chapter 1, Session 1

Since our last session concluded, our rag-tag team had managed to meet up with
one Jeffery Weatherington, a Constable in the Mesarite Marshalls early in the
morning at the train heading down to Edge. The Professor Archivist Tel Set
joined along with the party to get some measure of protection for the trip he
wanted to make to …

Without fanfare, the group boarded the train to Edge, spending the four day
trip cleaning and preparing their gear, and getting to know one another
better. Te Schwarm Chuuk made some offhand comments about his Cannibalism that
did not endear him to the Marshal, and from then on, Jeffery took many walks
from the cabin to "get some fresh air".

Upon arrival, the group retrieved their horses and headed into town. The
Marshall went to the local Constabulary to gain information from them and pay
proper courtesy, and the less conspicuous members of the party went to "The
Last Gulp" saloon to find and enquire upon Bill Paxton's sister, Lara
McFaddon.

