= Gateway

Gateway is a dense metropolis spread across the only pass between Darkpine Forest and The Dustbowl. Its run by a cartel of ruthless capitalists, and operates on the economics of the libertarian free market.

h2. History

Since its inception, [[Gateway]] has been a capitalists dream. With the city being the sole point of entry for caravans of wood from [[Darkpine Forest]], those who controlled the passage controlled the economy.

The pass isn't small enough to be choked by one person, however, and many competing companies sprung up and flourished, turning what was tantamount to a waystation into a thriving metropolis.

The leading capitalists weren't satisfied with the profits and competition they had, and fought amongst themselves both commercially and martially.

Eventually they fought themselves to a tense standstill, neither of them able to gain any ground against the others without suffering disproportionate losses. After what seemed like decades of this, a Cartel was formed between them, and conditions for everyone else in Gateway declined rapidly.

With the same ruthless tactics that left them on the top of the pile, they brutally but quietly quelled any resistance to their control. After a short while, no one dared speak up or resist in any way for fear of being ruined and killed. A workers revolt was inevitable.

h2. Connections

Straddling the line between The Dustbowl and Darkpine, Gateway doesn't have many connections, but those it has are held together with a desperate need; The Dustbowl needs wood, and Darkpine needs something.