= Chapter 1: The Basics

== The Hell

=== The Four Pillars

==== Exhaustion

==== Pain

==== Fear

==== Madness

=== Clarity
Clarity is the equivalent of DRYH Discipline. It is the measure of your character's ability to see past the surface of The Lie and perceive the nature of reality. Greater levels of Clarity allow access to new and exciting ways to get yourself mad or dead. At each level of clarity, a character is limited in the scope of their experience, gaining more and more freedom to explore the various parts of the Twilight Hell.

==== 0: "Faceless"
Either a background Extra or running entirely on Madness, characters with no Clarity have no Refresh to avoid Compels against their Aspects; therefore, they are driven entirely by their Nature. Barring drastic intervention to regain Clarity somehow, this is the end for a player character, as they can do nothing but be Compelled. They can't go anywhere they aren't compelled to. No free will, and barely exist.
_Tropes: [Faceless Masses](http://tvtropes.org/pmwiki/pmwiki.php/Main/FacelessMasses), [Mooks](http://tvtropes.org/pmwiki/pmwiki.php/Main/Mooks), [Cannon Fodder](http://tvtropes.org/pmwiki/pmwiki.php/Main/CannonFodder)_

==== 1: "Extra"
Slightly more perceptive than a "Faceless" but not quite a "Supporting Actor", An "Extra" has enough control over their choices that they can have a chance to pose an impediment to a players actions. A player reduced to 1 Clarity needs to be very careful not to lose any more, as at this point they have a very good chance of either crashing or becoming "Faceless". They can move and experience within the bounds of their archetypes' routine.
_Tropes: [Living Prop](http://tvtropes.org/pmwiki/pmwiki.php/Main/LivingProp), [Elite Mooks](http://tvtropes.org/pmwiki/pmwiki.php/Main/EliteMooks), [Red Shirt](http://tvtropes.org/pmwiki/pmwiki.php/Main/RedShirt)_
Free from simply traversing their routine, but can't exit their lifestyle.
_Tropes: [Mook Lieutenant](http://tvtropes.org/pmwiki/pmwiki.php/Main/MookLieutenant), [Mauve Shirt](http://tvtropes.org/pmwiki/pmwiki.php/Main/MauveShirt)_

==== 2: "Supporting Actor"
Has free movement within their genre, not just limited to their lifestyle.
_Tropes: [Superpowered Mooks](http://tvtropes.org/pmwiki/pmwiki.php/Main/SuperpoweredMooks), [Supporting Protagnonist](http://tvtropes.org/pmwiki/pmwiki.php/Main/SupportingProtagonist)_

==== 3: "Lead Role"
Can exit and move to other genres, but still can't escape their archetype.
_Tropes: [The Dragon](http://tvtropes.org/pmwiki/pmwiki.php/Main/TheDragon), [The Lancer](http://tvtropes.org/pmwiki/pmwiki.php/Main/TheLancer)_

==== 4: "???"
Free from the constraints of their archetype, but can't move outside of their domain.
_Tropes: [Big Bad](http://tvtropes.org/pmwiki/pmwiki.php/Main/BigBad), [Big Good](http://tvtropes.org/pmwiki/pmwiki.php/Main/BigGood)_

==== 5: "???"
Completely free. Can cross domains as needed.
_Tropes: [Bigger Bad](http://tvtropes.org/pmwiki/pmwiki.php/Main/BiggerBad)_

== The System

Playing a Twilight Hell game requires the Fate Core ruleset available from Evil Hat Publishing
footnote:[http://www.evilhat.com/home/fate-core/].

== The Story
