= Twilight Hell

The Twilight Hell is a meta-setting, in that it is broken down into a number of Domains, each again broken into Districts. The Wastelands fills the gaps in between the Domains and facilitates travel for those who have either gained enough Clarity to traverse and explore, or those unfortunates to have stumbled across it accidentally, with almost no hope of return.

The structure of the Twilight Hell aside, its inhabitants are numerous and varied. Each Domain homes a veritable continents-worth of population, though exact numbers or composition would be impossible to determine considering many of the inhabitants exist as a byproduct of the environment, rather than any biological processes. Truly, the same phenomena that generates the Nightmares that plague their lives is the same one that means there are always enough extras to fill in the crowd-scene and make a place feel busy.

== Sections

.link:concepts/README.adoc[Concepts]
Fundamentals for understanding how The Twilight Hell is put together.

.link:crunch/README.adoc[Crunch]
Rules and mechanics for gameplay.

.link:setting/README.adoc[Setting]
Setting information for the various Domains and Districts.

.link:adventures/README.adoc[Adventures]
Some sample adventures to play with your friends.

.link:legacy/README.adoc[Legacy]
Setting and rules information from before The Twilight Hell was a FATE game.

