= Metropolis
The Twilight Metropolis is a city of Gothic dreams and creeping nightmares. It appears as a circular expanse of miscellaneous and haphazard urban sprawl, radiating out from a central tower that looms ominously in the sky.

== The Tower of Glass
The central tower is visible from any part of the city, no matter how many buildings should be blocking the view. The 7 businessmen that run the city reside, and conduct their work from its interior, only occasionally leaving to lend a personal touch to whatever deals they deem require it. No-one can recall exactly what the businessmen look like, but that’s probably because they’re so busy all the time. Everyone knows someone who knows someone who met one of them once, but the details are a little blurry.

== Inhabitants
Its inhabitants are, for the most part, unaware of the nature of their lives, feeling comfortable to simply play the parts they are given. The inconsistencies and horrors that surround them are barely perceived, and quickly forgotten.

== The Monorail
There is a monorail track that runs a circular route around the tower, suspended above and around the rooftops. Every now and then, at no particular schedule, the carriages will pass by. Everyone knows that it must stop somewhere, but no-one seems to know where the stations are, and even fewer get so far as to think about it. It’s not like there aren’t people riding it.

== Districts
People with the same archetypical theme tend to congregate in districts, their worldview shaping the space around them and filtering their perceptions accordingly.
* [[Noire Central]]
* [[Pantechnica]]

== Notes

The stability of reality is directly proportional to distance from the tower.
The city is divided into 7 segments.

How many businessmen are there? 5? 7?
Must find that picture.

People with the same archetypical theme tend to congregate in districts, causing places like Noir Central to exist. As there is a Gamut, the boundaries of districts create fused Archetype combinations, but also tend to be less stable.