= Stress

h2. Endurance / Pain

h2. Energy / Exhaustion

All people get tired at some stage. They might never sleep, but they always get tired. As a story progresses, character will become exhausted with the constant physical and mental stress of their activities. As they get more exhausted, things get progressively harder.

h2. Courage / Fear

Franklin D. Roosevelt said at his inaugural speech a sentence that seems perfectly apt to highlight the danger of Fear in the Twilight hell:

bq. "So, first of all, let me assert my firm belief that the only thing we have to fear is fear itself—nameless, unreasoning, unjustified terror which paralyses needed efforts to convert retreat into advance."

The very fabric of reality is distorted by the Fear of those who dwell within it. Where the Stability of a [[Domain]] is weak, the effects of Fear, and the things that can manifest from it are stronger and more terrible.

h2. Ego / Madness

The Twilight Hell is contradictory at the best of times. The minds trapped within its clutches struggle to make what sense they can of it. The slow erosion of ones' worldview causes a spiral of madness that ends in nothing good.