= Aspects

Most of the material for this section is covered in the Fate Core rules. In this setting, there are only a few addendum that need to be made, and setting-specific advice for picking and compelling them.

Each character in the Twilight Hell is defined by their personality traits. Even the weakest, no-name, no-face background characters have at least two Aspects that give them form and substance; this includes equipment and Domains.

== Aspect Types

=== High Concept

This Aspect encompases the essence of a character, and sets the tone for all their adventures and behaviour. It should contain the character's profession if relevant, and any supernatural focuses if possessed.

=== Fatal Flaw

Each "thing" in the hell also has something that causes trouble for it.

=== Additional Aspects

For each point of Clarity, a "thing" gains another Aspect that further defines it's capabilities and personality

=== Temporary Aspects

By a player using discovery or as the result of a Consequence, Aspects may be added to a "thing" that further define it, without actually adding Clarity.

== Examples

=== Equipment

*High Concept:* Well-worn snub-nosed .38 revolver
*Fatal Flaw:* Dodgy serial number
*Clarity:* Modified to shoot magnum rounds
*Temporary:* Slick with sweat

=== Background Character

*High Concept:* Dangerous hoodlum
*Fatal Flaw:* Dumb as a brick
*Clarity:* Looking to leave crime behind
*Temporary:* Dodgy knee

=== Domain District

*High Concept:* Bustling Film-noire district of The Metropolis
*Fatal Flaw:* A place where hope goes to die
*Clarity:* A bar on every corner
*Temporary:* Good lighting

=== Narrative Character

*High Concept:* Hard-hitting reporter searching for the truth
*Fatal Flaw:* Plagued by spirits of the dead
*Clarity:* Eyes in the back of their head
*Temporary:* At one with the voices

== FATE Core references

=== Defining Aspects

[quote, Fate Core p56]
______________________________________________________________________________
An aspect is a phrase that describes something unique or noteworthy about
whatever it’s attached to. They’re the primary way you spend and gain fate
points, and they influence the story by providing an opportunity for a
character to get a bonus, complicating a character’s life, or adding to
another character’s roll or passive opposition.
______________________________________________________________________________

=== Defining Fate Points

[quote, Fate Core p56]
______________________________________________________________________________
GMs and players, you both have a pool of points called fate points you
can use to influence the game. You represent these with tokens, as we
mentioned in The Basics. Players, you start with a certain number of points
every scenario, equal to your character’s refresh. You’ll also reset to your
refresh rate if you ended a mid-scenario session with fewer fate points than
your rate. GMs, you get a budget of fate points to spend in every scene.
When your aspects come into play, you will usually spend or gain a fate
point.
______________________________________________________________________________

=== Types of Aspects

[quote, Fate Core p57]
______________________________________________________________________________
Every game of Fate has a few different kinds of aspects: game aspects,
character aspects, situation aspects, consequences, and boosts. They mainly
differ from one another in terms of what they’re attached to and how long
they last.
______________________________________________________________________________

==== Game Aspects

[quote, Fate Core p57]
______________________________________________________________________________
Game aspects are permanent fixtures of the game, hence the name. While
they might change over time, they’re never going to go away. If you’ve
already gone through game creation, you’ve already defined these—the current
or impending issues that you came up with. They describe problems
or threats that exist in the world, which are going to be the basis for your
game’s story.
Everyone can invoke, compel, or create an advantage on a game aspect at
any time; they’re always there and available for anyone’s use.
______________________________________________________________________________

==== Character Aspects

[quote, Fate Core p57]
______________________________________________________________________________
Character aspects are just as permanent, but smaller in scope, attached to an
individual PC or NPC. They describe a near-infinite number of things that
set the character apart, such as:

* Significant personality traits or beliefs (Sucker for a Pretty Face,
Never Leave a Man Behind, The Only Good Tsyntavian Is a Dead
Tsyntavian).
* The character’s background or profession (Educated at the Academy of
Blades, Born a Spacer, Cybernetic Street Thief).
* An important possession or noticeable feature (My Father’s
Bloodstained Sword, Dressed to the Nines, Sharp Eyed Veteran).
* Relationships to people and organizations (In League with the Twisting
Hand, The King’s Favor, Proud Member of the Company of Lords).
* Problems, goals, or issues the character is dealing with (A Price on My
Head, The King Must Die, Fear of Heights).
* Titles, reputations, or obligations the character may have (Self-
Important Merchant Guildmaster, Silver-Tongued Scoundrel,
Honor-Bound to Avenge My Brother).

You can invoke or call for a compel on any of your character aspects
whenever they’re relevant. GMs, you can always propose compels to any
PC. Players, you can suggest compels for other people’s characters, but
the GM is always going to get the final say on whether or not it’s a valid
suggestion.
______________________________________________________________________________

==== Situation Aspects

[quote, Fate Core p58]
______________________________________________________________________________
A situation aspect is temporary, intended to last only for a single scene
or until it no longer makes sense (but no longer than a session, at most).
Situation aspects can be attached to the environment the scene takes place
in—which affects everybody in the scene—but you can also attach them to
specific characters by targeting them when you create an advantage.
Situation aspects describe significant features of the circumstances the
characters are dealing with in a scene. That includes:

* Physical features of the environment (Dense Underbrush, Obscuring
Snowdrifts, Low Gravity Planet).
* Positioning or placement (Sniper’s Perch, In the Trees, Backyard).
* Immediate obstacles (Burning Barn, Tricky Lock, Yawning Chasm).
* Contextual details that are likely to come into play (Disgruntled
Townsfolk, Security Cameras, Loud Machinery).
* Sudden changes in a character’s status (Sand in the Eyes, Disarmed,
Cornered, Covered in Slime).

Who can use a situation aspect depends a lot on narrative context—
sometimes it’ll be very clear, and sometimes you’ll need to justify how you’re
using the aspect to make sense based on what’s happening in the scene.
GMs, you’re the final arbiter on what claims on an aspect are valid.
Sometimes situation aspects become obstacles that characters need to
overcome. Other times they give you justification to provide active opposition
against someone else’s action.
______________________________________________________________________________

==== Consequences

[quote, Fate Core p58]
______________________________________________________________________________
A consequence is more permanent than a situation aspect, but not quite as
permanent as a character aspect. They’re a special kind of aspect you take in
order to avoid getting taken out in a conflict, and they describe lasting
injuries or problems that you take away from a conflict (Dislocated Shoulder,
Bloody Nose, Social Pariah).
Consequences stick around for a variable length of time, from a few
scenes to a scenario or two, depending on how severe they are. Because of
their negative phrasing, you’re likely to get compelled a lot when you have
them, and anyone who can justifiably benefit from the consequence can
invoke it or create an advantage on it.
______________________________________________________________________________

==== Boosts

[quote, Fate Core p58]
______________________________________________________________________________
Boosts are a super-transient kind of aspect. You get a boost when you’re
trying to create an advantage but don’t succeed well enough, or as an added
benefit to succeeding especially well at an action. You get to invoke them for
free, but as soon as you do, the aspect goes away.
If you want, you can also allow another character to invoke your boost, if
it’s relevant and could help them out.
______________________________________________________________________________

=== What Aspects Do

In Fate, aspects do two major things: they tell you what’s important about
the game, and they help you decide when to use the mechanics.

==== Importance

Your collection of game and character aspects tell you what you need to
focus on during your game. Think of them as a message from yourself to
yourself, a set of flags waving you towards the path with the most fun.
GMs, when you make scenarios for Fate, you’re going to use those aspects,
and the connections between aspects, to generate the problems your PCs
are going to solve. Players, your aspects are the reason why your PC stands
out from every other character who might have similar skills—lots of Fate
characters might have a high Fight skill, but only Landon is a Disciple of
the Ivory Shroud. When his path as a disciple comes into play, or the Ivory
Shroud takes action, it gives the game a personal touch that it wouldn’t have
had otherwise.
The game aspects do something similar on a larger scale—they tell us why
we care about playing this particular game in the first place, what makes
it concrete and compelling to us. We can all say, “Oh, we like space opera
games,” but until we drill down to the specifics of a universe where people
will do Anything for Survival, and where The Empire is Everywhere, we
don’t really have anything to attach our interest to.
Situation aspects make the
moment-to-moment interactions
of play interesting
by adding color and depth
to what might otherwise be
a boring scene. A fight in a
tavern is generic by nature—
it could be any tavern, anywhere.
But when you add
the aspect Huge Bronze
Devil Statue to the scene,
and people bring it into play,
it becomes “that fight we
were in at the Bronze Devil,
when I smashed that guy’s
head into the statue.” The
unique details add interest
and investment.

Deciding When to Use Mechanics
Because aspects tell us what’s important, they also tell us when it’s most
appropriate to use the mechanics to deal with a situation, rather than just
letting people decide what happens just by describing what they do.
GMs, this comes up for
you most often when you’re
trying to figure out whether
to require a player to roll
dice. If a player says, “I climb
this ladder and grab the idol,”
and there’s nothing special
about the ladder or the idol,
then there’s no real reason to
require an overcome action
to grab it. But if the situation
aspects tell you that the ladder
is a Rotting Rope Ladder and
the idol is Protected by the
Wrath of the Gods, then you
suddenly have an element of
pressure and risk that makes
it worth going to the dice for.
Players, this comes up for
you most often when invoking
your aspects and considering
compels. Your aspects
highlight what makes your
character an individual, and
you want to play that up,
right? So when the opportunity
comes up to make your
character more awesome by
invoking, go for it! When you
see an opportunity to influence
the story by suggesting
a compel for your character,
do it! The game will be much
richer for it as a whole.
Aspects and
Fate Points
60
Chapter 4
Making a Good Aspect
Because aspects are so important to the game, it’s important to make the
best aspects you can. So, how do you know what a good aspect is?
The best aspects are double-edged, say more than one thing, and keep
the phrasing simple.
Double-Edged
Players, good aspects offer a clear benefit to your character while also providing
opportunities to complicate their lives or be used to their detriment.
An aspect with a double-edge is going to come up in play more often than
a mostly positive or negative one. You can use them frequently to be awesome,
and you’ll be able to accept more compels and gain more fate points.
Try this as a litmus test—list two ways you might invoke the aspect, and
two ways someone else could invoke it or you could get a compel from it. If
the examples come easily to mind, great! If not, add more context to make
that aspect work or put that idea to the side and come up with a new aspect.
Let’s look at an aspect like Computer Genius. The benefits of
having this aspect are pretty obvious—any time you’re hacking
or working with technology, you could justify invoking it. But it
doesn’t seem like there’s a lot of room for that aspect to work
against you. So, let’s think of a way we can spice that up a bit.
What if we change that aspect to Nerdy McNerdson? That still
carries the connotations that would allow you to take advantage
of it while working with computers, but it adds a downside—
you’re awkward around people. This might mean that you could
accept compels to mangle a social situation, or someone might
invoke your aspect when a fascinating piece of equipment distracts
you.
GMs, this is just as true of your game and situation aspects. Any feature
of a scene you call out should be something that either the PCs or their foes
could use in a dramatic fashion. Your game aspects do present problems,
but they also should present ways for the PCs to take advantage of the
status quo.
Aspects and
Fate Points
61
Fate Core
Say More Than One Thing
Earlier, we noted several things that a character aspect might describe: personality
traits, backgrounds, relationships, problems, possessions, and so
forth. The best aspects overlap across a few of those categories, because that
means you have more ways to bring them into play.
Let’s look at a simple aspect that a soldier might have: I Must
Prove Myself. You can invoke this whenever you’re trying to do
something to gain the approval of others or demonstrate your
competence. Someone might compel it to bait you into getting
into a fight you want to avoid, or to accept a hardship for the
sake of reputation. So we know it has a double edge, so far so
good.
That’ll work for a bit, but eventually this aspect will run out of
steam. It says just one thing about the character. Either you’re
trying to prove yourself, or this aspect isn’t going to come up.
Now tie that aspect in with a relationship to an organization:
The Legion Demands I Prove Myself. Your options open up a
great deal. Not only do you get all the content from before, but
you’ve introduced that the Legion can make demands of you,
can get you into trouble by doing things you get blamed for, or
can send NPC superiors to make your life difficult. You can also
invoke the aspect when dealing with the Legion, or with anyone
else who might be affected by the Legion’s reputation. Suddenly,
that aspect has a lot more going on around it.
GMs, for your situation aspects, you don’t have to worry about this as
much, because they’re only intended to stick around for a scene. It’s much
more important for game and character aspects to suggest multiple contexts
for use.
Character
Aspects
p. 57
* I Must Prove Myself
* The Legion Demands I Prove
Myself
Aspects and
Fate Points
62
Chapter 4
Clear Phrasing
Because aspects are phrases, they come with all the ambiguities of language.
If no one knows what your aspect means, it won’t get used enough.
That isn’t to say you have to avoid poetic or fanciful expression. Just a
Simple Farmboy isn’t quite as fetching as Child of Pastoral Bliss. If that’s
the tone your game is going for, feel free to indulge your linguistic desires.
However, don’t do this at the expense of clarity. Avoid metaphors and
implications, when you can get away with just saying what you mean. That
way, other people don’t have to stop and ask you during play if a certain
aspect would apply, or get bogged down in discussions about what it means.
Let’s look at Memories, Wishes, and Regrets. There’s something
evocative about the phrase. It suggests a kind of melancholy
about the past. But as an aspect, I don’t really know what it’s
supposed to do. How does it help you? What are the memories
of? What did you wish for? Without some concrete idea of what
the aspect’s referring to, invoking and compelling it is pretty
much impossible.
Suppose we talk about this some, and you specify that you
were going for this idea that your character was scarred from
years spent in the setting’s last great war. You killed people you
didn’t want to kill, saw things you didn’t want to see, and pretty
much had all your hope of returning to a normal life taken away.
I think this is all fantastic, and I suggest we call it Scars from
the War. Less poetic, maybe, but it directly references all the
stuff you’re talking about, and gives me ideas about people from
your past I may be able to bring back into your life.
If you’re wondering if your aspect is unclear, ask the people at the table
what they think it means.
* Memories, Wishes, and Regrets
* Scars from the War
Aspects and
Fate Points
63
Fate Core
If You Get Stuck
Now you know what makes for a good aspect, but that doesn’t narrow down
your potential choices any—you still have a nearly infinite set of topics and
ideas to choose from.
If you’re still stuck about what to choose, here are some tips to make
things a little easier on you.
Sometimes, It’s Better Not to Choose
If you can’t think of an aspect that really grabs you and the other people at
the table, you’re better off leaving that space blank, or just keeping whatever
ideas you had scribbled in the margins. Sometimes it’s much easier to wait
for your character to get into play before you figure out how you want to
word a particular aspect.
So when in doubt, leave it blank. Maybe you have a general idea of the
aspect but don’t know how to phrase it, or maybe you just have no idea.
Don’t worry about it. There’s always room during the game to figure it out
as you go.
The same thing is true if you have more than one idea that seems juicy,
but they don’t work together and you don’t know which one to pick. Write
them all down in the margins and see which one seems to really sing in play.
Then fill the space in later, with the one that gets the most mileage.
Always Ask What Matters and Why
We said above that aspects tell you why something matters in the game and
why we care about it. This is your primary compass and guide to choosing
the best possible aspect. When in doubt, always ask: what do we really care
about here, and why?
The events of the phases should help you figure out what your aspect
should be. Don’t try to summarize the events of the phase or anything like
that with your aspect—remember, the point is to reveal something important
about the character. Again, ask yourself what really matters about the
phase:
• What was the outcome? Is that important?
• Did the character develop any important relationships or connections
during this phase?
• Does the phase help establish anything important about the character’s
personality or beliefs?
• Did the phase give the character a reputation?
• Did the phase create a problem for the character in the game world?
The Phase Trio
p. 38
Aspects and
Fate Points
64
Chapter 4
Assume that each question ends with “for good or ill”—these features,
relationships, and reputations aren’t necessarily going to be positive, after
all. Developing a relationship with a nemesis is as juicy as developing one
with your best friend.
If there’s more than one option, poll the other players and GM to see
what they find interesting. Remember, you should all be helping each other
out—the game works best if everyone’s a fan of what everyone else is doing.
During Cynere’s phase three, Lily states that she complicated
Zird’s story by showing up at an opportune moment and stealing
the artifact that Zird stole from his rivals. Eventually the artifact
returns to Zird’s hands.
She’s trying to tease out what the best aspect would be, and
she doesn’t have a whole lot of information to go on. Going
through the questions above, we see a lot of potential options—
she showed off her underhandedness, she definitely suggested
a relationship with Zird of some kind, and Zird’s rivals might now
have a beef with her as well.
Lily polls the rest of the group, and after some talking, everyone
seems to be pretty enthused about Cynere having some kind
of aspected connection to Zird—they did all grow up in the same
village, after all. She decides on I’ve Got Zird’s Back, because it’s
specific enough to be invoked and compelled, but leaves room
for development later on in the game.
Phase Three:
Crossing Paths
Again
p. 44
Aspects and
Fate Points
65
Fate Core
Vary It Up
You don’t want all your aspects to describe the same kind of thing. Five
relationships means that you can’t use your aspects unless one of them is in
play, but five personality traits means that you have no connection to the
game world. If you’re stuck on what to pick for an aspect, looking at what
kinds of things your other aspects describe may help you figure out which
way to go for the current phase.
Lenny ends up with Disciple of the Ivory Shroud and The
Manners of a Goat as Landon’s high concept and trouble. So far,
this is a pretty straightforward character—a violent type whose
mouth and demeanor are always getting him into trouble.
Lenny does his phase one and explains to us that Landon was
a miscreant and street rat that grew up practically as an orphan—
his parents were around, but never really paid too much attention
to him or spent effort reining him in. He eventually decided
to enlist in the town militia after someone saved him from a clobbering
in a bar fight and suggested he do something worthwhile
with his life.
Amanda asks him what really matters about this phase, and
Lenny ponders a bit. Landon’s first two aspects are heavy on
personal description—he doesn’t have a lot of relationships yet.
So Lenny focuses on that and decides he wants a connection to
the guy who pulled him into the militia.
They end up naming that guy Old Finn, Landon ends up with
the aspect I Owe Old Finn Everything, and Amanda now has a
new NPC to play with.
Phase
One
p. 40
I Owe Old Finn Everything
CHARACTER IDEA
High Concept Aspect
Trouble Aspect
Name
PHASE TRIO
Phase One: Your Adventure
Phase One Aspect
Phase Two: Crossing Paths
Phase Two Aspect
Phase Three: Crossing Paths Again
Phase Three Aspect
REFRESH
CORE SYSTEM
Character Creation Worksheet
Zird the Arcane hires Landon to quietly break into the Tower of
Unrest at the Collegia. When their cover is blown, Landon kicks out
the tower’s supporting pillars. The two escape as the structure comes
crashing down.

==== Making a Good Aspect



==== If You Get Stuck

==== Invoking Aspects

==== Compelling Aspects

==== Using Aspects for Roleplaying

==== Removing or Changing an Aspect

==== Creating and Discovering New Aspects in Play

==== The Fate Point Economy

