= The Stunts
:toc: right

== Stunt Rubrics

=== Add a New Action to a Skill

__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
The most basic option for a stunt is to allow a skill to do something
that it normally can't do. It adds a new action onto the base skill in
certain situations, for those with this stunt. This new action can be
one that's available to another skill (allowing one skill to swap for
another under certain circumstances), or one that's not available to any
skill. (Fate Core, p.89)
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

=== Add a Bonus to an Action

[quote, p.90, Fate Core]
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
Another use for a stunt is to give a skill an automatic bonus under a
particular, very narrow circumstance, effectively letting a character
specialize in something. The circumstance should be narrower than what
the normal action allows, and only apply to one particular action or
pair of actions. +
The usual bonus is +2 to the skill total. However, if you want, you can
also express the bonus as two shifts of additional effect after the roll
succeeds, if that makes more sense. Remember, higher shifts on a roll
allow your action to be more effective in certain ways. +
You can also use this to establish any effect worth two shifts as an
additional benefit of succeeding at the skill roll. This might be Fair
(+2) passive opposition, the equivalent of a 2-point hit, a mild
consequence, or an advantage that takes Fair (+2) opposition to remove.
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

=== Create a Rules Exception

[quote, p.91, Fate Core]
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
Finally, a stunt can allow a skill to make a single exception, in a
narrow circumstance, for any other game rule that doesn't precisely fit
into the category of an action. The Challenges, Contests, and Conflicts
chapter is full of different little rules about the circumstances under
which a skill can be used and what happens when you use them. Stunts can
break those, allowing your character to stretch the boundaries of the
possible. +
The only limit to this is that a stunt can't change any of the basic
rules for aspects in terms of invoking, compelling, and the fate point
economy. Those always remain the same.
______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

=== Other Rubrics

==== Flexible Stunts

[quote, p.34, Fate System Toolkit]
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
In Fate Core, stunts are tied explicitly to skills. What if you want
your stunts to be skill-agnostic, or tied to multiple skills, or tied to
something else entirely different, like an aspect or piece of gear or a
stress track?
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

===== Aspected Stunts

[quote, p.34, Fate System Toolkit]
________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
For stunts which are tied to aspects, you might view some of their
effects as narrowly defined free invocations. Other aspected stunts
might require an invocation, as *Ally's Shield* does, but give something
extra or particularly unusual when the aspect is invoked. Such effects
should be more potent than a "vanilla" invocation. You could even design
a stunt that triggers under particular kinds of compels -just be careful
you don't end up neutering the downside with the resulting benefit.
________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

==== Triggered Effects

[quote, p.35, Fate System Toolkit]
_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
When you use this stunt mechanic, you create stunts that trigger under a
specific narrative condition, require a skill roll, and have a specific
effect as a result. Stunts like this are a great way to encourage
players to do the kinds of things you want to see them do in the game,
as those stunts directly reward doing those things.
_________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

==== Broad Stunts

[quote, p.35, Fate System Toolkit]
____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
If you're looking for more variety in your stunts than a +2 or its
equivalent, consider the idea of a broad stunt that offers a +1 to two
or three things. These could be three different actions within the same
skill, or could branch across multiple related skills. If you're going
to allow broad stunts like this, watch out for the overlaps in stunt
combinations: you don't want two broad stunts giving the net effect of
three +2s for the price of only two stunts.
____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

==== Combined Stunts

[quote, p.35, Fate System Toolkit]
___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
If you want to offer particularly potent stunts, consider bundling the
benefit of multiple stunts together to produce a single big effect. For
example, you could create a stunt that provides a monstrous 4-shift
effect -that's a combination of two stunts, and as such would cost two
refresh. (You may recognize this as the method used for constructing the
supernatural powers in _The Dresden Files_ RPG.) This kind of focused
benefit can throw a game out of whack quickly, though. Consider limiting
access to such "super-stunts," either in quantity-e.g., "everyone only
gets one double-stunt"-or in selection and permission-"only these stunts
are available to werewolves."
___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

