= Skills

* Athletics
* Burglary
* Contacts
* Crafts
* Deceive
* Drive
* Fight
* Investigate
* Lore
* Notice
* Endurance
* Provoke
* Rapport
* Resources
* Shoot
* Stealth
* Survival
* Will

== Purchase

Each level of a skill costs 1 Character Point. However, for every skill of a
given level above 1, there must be at least one other skill at one level
lower. For example:

* To have a skill at 2, you need to have another skill at 1.
  ```
  O
  O
  ```
* To have 2 skills at 2, you need to have 2 other skills at 1.
  ```
  OO
  OO
  ```
* To have a skill at 3, you need to have another skill at 2, and yet another
  skill at 1.
  ```
  O
  O
  O
  ```

So taking those specific examples into account, A gunslinger with 20cp spent
on skills can have the following configurations:

```
4  OO  O     O
3  OO  OO    O      OOO
2  OO  OOO   OOOO   OOO
1  OO  OOOO  OOOOO  OOOOO etc.
```

This is called the column system, and for the purposes of the game, the
columns are fixed at 5, meaning the maximum number of skills you can posess at
a particular level is 5. In addition, skills are capped at 3 + ( Clarity / 2
).

== Use

=== Combinations

Frequently, a challenge can't be solved within the domain of a single skill,
so this is handled mechanically by taking the lowest value of all required
skills.

For instance, if a character has an opportunity to notice an obscure detail
about another character's revolver, such as a manufacturing defect in its
particular run, they would roll the lowest of Shoot, Lore, and Notice.

If the detail to be noticed is more ordinary, such as the safety catch being
engaged, they may only have to roll the lowest of Shoot and Notice.

However, if it's something that doesn't require an intimate understanding of
firearms or their maintenance, such as the word 'replica' being engraved on
the action, only Notice would be necessary.

